import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../../assets/vendor/bootstrap/css/bootstrap.min.css'
import '../../assets/vendor/font-awesome/css/font-awesome.min.css'
import '../../assets/vendor/animate-css/vivify.min.css'
import '../../assets/vendor/c3/c3.min.css'
import '../../assets/vendor/chartist/css/chartist.min.css'
import '../../assets/vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.css'
import '../../assets/vendor/toastr/toastr.min.css'
import '../../assets/globals.css'
import Header from "@/src/components/header";
import Sidebar from "@/src/components/sidebar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Head>
      <script src="../../assets/bundles/c3.bundle.js" async />
      <script src="../../assets/bundles/chartist.bundle.js" async />
      <script src="../../assets/vendor/toastr/toastr.min.js" async />

      <script src="../../assets/bundles/mainscripts.bundle.js" async/>
      <script src="../../assets/js/index2.js" async/>

      <script src="../../assets/bundles/libscripts.bundle.js" async />
      <script src="../../assets/bundles/vendorscripts.bundle.js" async />
    </Head>
    <body className={inter.className}>
    <div id="wrapper">
      <Header/>
      <Sidebar/>
      <div id='main-content'>
        {children}
      </div>
    </div>
    </body>
    </html>
  );
}
